[package]
name = "process_viewer"
version = "0.0.2"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A process viewer GUI"
repository = "https://github.com/GuillaumeGomez/process-viewer"
license = "MIT"
homepage = "https://github.com/GuillaumeGomez/process-viewer"

readme = "README.md"

keywords = ["GUI", "process", "viewer", "gtk"]

[dependencies]
gtk-sys = { git = "https://github.com/gtk-rs/sys" }
pango-sys = { git = "https://github.com/gtk-rs/sys" }
gtk = { git = "https://github.com/gtk-rs/gtk" }
glib = { git = "https://github.com/gtk-rs/glib" }
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
gdk = { git = "https://github.com/gtk-rs/gdk" }
libc = "0.2"
sysinfo = "0.1.15"

[[bin]]
name = "process_viewer"
