[package]
name = "process_viewer"
version = "0.0.17"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A process viewer GUI"
repository = "https://github.com/GuillaumeGomez/process-viewer"
license = "MIT"
homepage = "https://github.com/GuillaumeGomez/process-viewer"

readme = "README.md"

keywords = ["GUI", "process", "viewer", "gtk"]

[dependencies]
cairo-rs = "0.4"
gdk = "0.8"
gdk-pixbuf = "0.4"
gio = "0.4"
glib = "0.5"
gtk = "0.4.1"
pango = "0.4"
sysinfo = "0.5"
libc = "0.2"

[[bin]]
name = "process_viewer"
path = "src/process_viewer.rs"

[features]
default = ["gio/v2_34"]
