[package]
name = "process_viewer"
version = "0.0.1"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A process viewer GUI"
repository = "https://github.com/GuillaumeGomez/process-viewer"
license = "MIT"
homepage = "https://github.com/GuillaumeGomez/process-viewer"

readme = "README.md"

keywords = ["GUI", "process", "viewer", "gtk"]

[dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk" }
glib = { git = "https://github.com/gtk-rs/glib" }
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
gdk = { git = "https://github.com/gtk-rs/gdk" }
sysinfo = "0.1.10"

[[bin]]
name = "process_viewer"
