[package]
name = "processus_viewer"
version = "0.0.1"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>]

[dependencies.gtk]
git = "https://github.com/rust-gnome/gtk.git"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib.git"

[dependencies.sysinfo]
git = "https://github.com/guillaumegomez/sysinfo.git"

[[bin]]
name = "processus_viewer"
