[package]
name = "process_viewer"
version = "0.0.8"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A process viewer GUI"
repository = "https://github.com/GuillaumeGomez/process-viewer"
license = "MIT"
homepage = "https://github.com/GuillaumeGomez/process-viewer"

readme = "README.md"

keywords = ["GUI", "process", "viewer", "gtk"]

[dependencies]
cairo-rs = "0.2"
gdk = "0.6"
gdk-pixbuf = "0.2"
glib = "0.3"
gtk = "0.2"
libc = "0.2"
pango = "0.2"
sysinfo = "0.3"

[[bin]]
name = "process_viewer"
path = "src/process_viewer.rs"
