[package]
name = "process_viewer"
version = "0.0.13"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A process viewer GUI"
repository = "https://github.com/GuillaumeGomez/process-viewer"
license = "MIT"
homepage = "https://github.com/GuillaumeGomez/process-viewer"

readme = "README.md"

keywords = ["GUI", "process", "viewer", "gtk"]

[dependencies]
cairo-rs = "0.3"
gdk = "0.7"
gdk-pixbuf = "0.3"
gio = "0.3"
glib = "0.4"
gtk = "0.3"
pango = "0.3"
sysinfo = "0.4"
libc = "0.2"

[[bin]]
name = "process_viewer"
path = "src/process_viewer.rs"
